import MainNavbar from "@/components/main-navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SocketioProvider from "@/components/providers/socketio-provider";
import ColyseusProvider from "@/components/providers/colyseus-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SocketioProvider>
          <ColyseusProvider>
            <MainNavbar />
            <main className="container pt-4">{children}</main>
          </ColyseusProvider>
        </SocketioProvider>
      </body>
    </html>
  );
}
